package claudeagent.documentImport;

import java.util.ArrayList;
import java.util.List;

public class DocumentChunker {

	public static List<String> chunkText(String text, int targetSize, int overlap) {
		List<String> chunks = new ArrayList<String>();
		StringBuilder sb = new StringBuilder();
		for (String paragraph: text.split("\\n\\s*\\n")) {
			paragraph = paragraph.trim();
			if (paragraph.isEmpty()) {
				continue;
			} else if (sb.length() + paragraph.length() > targetSize && sb.length() > 0) {
				chunks.add(sb.toString().trim());
				String tail;
				if (sb.length() > overlap) {
					tail = sb.toString().substring(sb.length() - overlap);
				} else {
					tail = sb.toString();
				}
				sb = new StringBuilder(tail);
			}
			sb.append(paragraph).append("\n\n");
			while (sb.length() > targetSize) {
				chunks.add(sb.toString().substring(0, targetSize).trim());
				String tail = sb.toString().substring(targetSize - overlap);
				sb = new StringBuilder(tail);
			}
		}
		if (sb.length() > 0) {
			chunks.add(sb.toString().trim());
		}
		return chunks;
	}
	
	public static void main (String[] args) {
		List<String> chunky = chunkText(loremIpsum, 768, 20);
		for (String s: chunky) {
			System.out.println(s+"\n---------------------------------------------------");
		}
		
	}
	
	
	
	


	
	
	
	
	
	static String loremIpsum  = """
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque justo sem, laoreet eget efficitur eu, ultrices at risus. Aliquam erat volutpat. Quisque quis scelerisque ex, sit amet faucibus leo. Pellentesque at molestie sapien, at blandit arcu. Duis auctor felis quis dolor molestie, ut congue sem pellentesque. Aliquam laoreet gravida nunc, et gravida metus eleifend a. Curabitur rutrum dolor semper pulvinar sollicitudin.
			Etiam gravida ultrices nisi consectetur rhoncus. Nulla lobortis pharetra facilisis. Proin aliquam pretium commodo. Maecenas vestibulum elementum blandit. Nunc lorem nibh, rutrum quis velit id, pulvinar pulvinar massa. Sed commodo interdum sapien nec commodo. Donec sed eros et justo porttitor facilisis. Vestibulum at tristique neque, et tincidunt orci. Pellentesque lacinia metus eget lacus euismod, a gravida libero dignissim. In hac habitasse platea dictumst. Nulla vel tincidunt quam, eget aliquam lectus. Suspendisse ac tincidunt arcu. Proin eget lectus id tellus hendrerit dapibus.
			Donec luctus ex at mi mollis tincidunt. Integer non eros quis lacus ultrices tristique. Aliquam erat volutpat. Sed efficitur dolor sit amet massa venenatis euismod. Praesent in maximus nulla, ut condimentum nisi. Vivamus erat nunc, aliquam sed sollicitudin sit amet, suscipit vitae sapien. Aliquam ultricies magna libero, vehicula auctor odio sagittis ac. Nunc porttitor sit amet orci at ornare. Sed in pellentesque nulla, bibendum auctor nisl. Morbi vehicula lobortis libero gravida congue. Ut id dui dolor. Nam ac sapien eget diam ultrices dignissim vel ac elit. Donec sed nisl vitae mi elementum tincidunt. Ut fringilla purus vel risus pellentesque, vel sollicitudin eros condimentum. Nunc est purus, faucibus nec eleifend nec, laoreet ac nulla. Praesent molestie, est vitae tempus congue, lorem turpis porta est, nec sagittis massa ligula at dolor.
			Morbi tincidunt porta arcu, vel egestas sem suscipit sed. Morbi eu ornare enim, a vulputate nunc. Nulla et ipsum ac eros bibendum convallis. Duis cursus sapien et metus sollicitudin, ullamcorper sollicitudin nibh venenatis. Morbi nibh ante, tempus vel varius sit amet, semper quis nunc. Fusce a leo egestas, fringilla dui sed, bibendum magna. In quam velit, rhoncus pharetra efficitur id, finibus vitae risus. Cras ornare, libero eu fermentum semper, est ligula feugiat justo, in aliquam leo magna et diam. Suspendisse potenti. Duis eu dolor et purus tempus eleifend.
			Proin et nulla eu augue sodales tincidunt ut et tellus. Suspendisse faucibus ante ut pharetra sodales. Nullam pharetra tellus at sapien efficitur varius. Morbi malesuada justo sed massa ultrices cursus. Ut eget molestie odio, et malesuada justo. Ut scelerisque feugiat est at facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris rhoncus iaculis urna id imperdiet. Nulla fringilla arcu a euismod vehicula. Aenean ex nisi, pretium quis ultricies at, congue commodo neque. Quisque dapibus malesuada sem, sit amet interdum mauris rhoncus quis. Vivamus condimentum sapien non vulputate ultrices. Vivamus non placerat augue, in pharetra mi. Vivamus cursus justo in egestas vehicula. Proin consequat pellentesque tortor a convallis. Praesent sed commodo orci.
			Suspendisse potenti. Nulla vehicula arcu ut ultrices tincidunt. Praesent a sodales nisi. In eget nisi vitae mauris semper accumsan. Maecenas pretium tincidunt nisi, id elementum augue bibendum tincidunt. Donec gravida, tellus at iaculis rhoncus, odio eros ultrices erat, vitae ultrices enim tortor eu eros. Maecenas ut ultricies turpis. Sed et pellentesque erat, non efficitur lacus. Maecenas auctor pellentesque mauris, vel porta magna convallis a. Vivamus efficitur eros nibh, a gravida sapien vestibulum ac.
			Nulla dictum nunc velit, in scelerisque dui mattis sed. Vestibulum ac pretium enim. Quisque sagittis ut quam sed suscipit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In metus nisi, volutpat vel volutpat id, tempus ac quam. Aliquam magna tellus, ultricies eget nisl eget, ullamcorper convallis ante. Curabitur dapibus dui id ullamcorper tincidunt. Vestibulum venenatis, magna at feugiat consequat, nunc urna dignissim justo, nec aliquam erat orci eget mauris. Vestibulum ac lacus eget neque pellentesque mattis.
			Nulla molestie sed lacus eu cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis ligula lectus, hendrerit sit amet justo ut, aliquet viverra arcu. In lectus risus, pellentesque sit amet mauris ut, consectetur accumsan metus. Vivamus consequat quis orci at ullamcorper. Quisque magna nisl, rutrum ac volutpat a, mollis ut magna. Sed pharetra imperdiet posuere. Pellentesque tortor orci, fermentum eget dignissim non, consectetur sed libero. Nam erat ipsum, elementum eu posuere eget, sagittis at tellus. Ut id nisi id tortor finibus pulvinar. Pellentesque dapibus arcu ipsum. In ornare a libero ut commodo. Aliquam at mollis ligula. Praesent interdum elementum felis.
			Pellentesque non enim pretium, efficitur felis nec, consectetur felis. Suspendisse nec faucibus nunc. Duis sem tellus, suscipit et lacinia nec, vestibulum eu nisl. In quis aliquam tortor, et vulputate mi. Mauris ac pellentesque ipsum, id cursus diam. Praesent id vestibulum augue. Sed auctor lectus at elit vulputate porttitor. Mauris mollis tincidunt quam vel dapibus.
			Phasellus at ornare dolor. Pellentesque sit amet condimentum mi. Nullam eu scelerisque nisi. Morbi imperdiet eros nulla, in pretium elit mattis vitae. Aliquam aliquet elit in nisl aliquam, et eleifend lectus consectetur. Quisque egestas ornare nulla. Nunc a rhoncus purus. Fusce tempor volutpat neque vel fringilla. Vestibulum eleifend purus id tempor fringilla. Nunc dapibus lorem et ipsum mattis laoreet. Curabitur commodo ultrices elementum. Maecenas viverra urna ac mauris pretium fringilla. Phasellus eu nibh nisl. Sed rutrum nibh at erat maximus, id sodales ligula pretium. Etiam rhoncus condimentum vestibulum. Mauris viverra cursus sem ac sodales.
			Duis non consectetur ligula. Etiam a sapien eget nulla ornare suscipit non ac magna. Quisque dapibus placerat imperdiet. Aenean libero dui, vulputate mollis risus vel, dignissim rhoncus quam. Nunc ultrices purus eu justo commodo malesuada. Nunc a mauris in turpis sagittis vulputate a id sem. Suspendisse et rutrum metus, et luctus tellus. Sed vel fringilla orci. Etiam eu molestie massa.
			Nam egestas euismod augue eget bibendum. Cras vehicula nunc nec ligula viverra, nec convallis lectus ultrices. Nam at ex vel odio accumsan molestie. Aenean et odio nec nunc rhoncus venenatis. Quisque accumsan leo neque, nec fringilla dui ultricies sit amet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque eu augue non sem iaculis tempus vel nec turpis.
			Aliquam sed ex accumsan, efficitur quam ac, interdum tortor. Nullam faucibus neque vel placerat cursus. Duis viverra, neque sit amet suscipit vestibulum, nisl felis aliquet nunc, eu porta lectus eros eu dolor. Suspendisse id ultricies sem, eget semper ante. Suspendisse sollicitudin elementum ligula, in suscipit dolor sagittis at. Sed tristique consectetur odio, vel aliquet nunc facilisis nec. Pellentesque eget quam in leo tincidunt euismod quis a lectus. Curabitur porttitor massa sit amet ultrices sodales. Sed ultricies augue turpis, eget dictum quam facilisis id. Vivamus bibendum pulvinar semper. Proin pellentesque bibendum diam eget rutrum. Vestibulum venenatis sem quam, sed tristique dui varius auctor.
			Aenean tempus lectus odio, at eleifend nibh ultricies id. Nulla eu sollicitudin purus, mattis interdum orci. Nullam id diam nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nullam bibendum blandit dui et sollicitudin. Pellentesque sed pulvinar tellus. In et laoreet purus. Cras mattis pharetra urna nec tincidunt. Cras maximus felis ac nunc facilisis, sed fringilla velit pharetra. In hac habitasse platea dictumst. Sed non enim risus. Duis fermentum interdum velit quis convallis. Maecenas mi ante, semper in nisl et, feugiat tincidunt arcu. Integer dapibus venenatis ipsum, ut viverra arcu ultricies at.
			Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec dictum rhoncus magna ut tempus. Nulla facilisi. Aenean lobortis vitae neque a gravida. Nam arcu purus, scelerisque sed vulputate at, tristique non mauris. Vivamus posuere massa at neque vehicula, non commodo dolor dapibus. Maecenas nec auctor ante. Vestibulum sed mauris laoreet, malesuada elit nec, dapibus nibh.
			Nam a mi felis. Donec tincidunt ultrices odio, eget malesuada lorem fringilla et. Integer quam ligula, vestibulum quis cursus eget, cursus vel nisi. Curabitur ultricies accumsan lorem sit amet mollis. Ut varius felis quis auctor viverra. Praesent dictum neque tortor, nec suscipit ligula scelerisque facilisis. Suspendisse porttitor magna in felis venenatis eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque ut faucibus ante, eget finibus enim.
			Maecenas velit mi, facilisis sit amet vestibulum quis, pulvinar a risus. Fusce fermentum erat ligula, ut ornare nulla suscipit id. Aliquam dapibus sem dapibus eros tempus egestas. Phasellus consectetur massa non purus accumsan, venenatis interdum nunc pulvinar. Aenean dignissim, purus rutrum finibus fringilla, nisi lacus pellentesque erat, id fringilla felis lacus at velit. Fusce sit amet odio pellentesque, finibus purus vel, finibus odio. Proin feugiat facilisis urna non imperdiet.
			Fusce a justo venenatis, pellentesque mi eget, vulputate elit. Ut varius maximus ullamcorper. Integer nec suscipit velit. Suspendisse ullamcorper accumsan condimentum. Vestibulum libero elit, volutpat in posuere et, ullamcorper et enim. Mauris ut porta ipsum. Pellentesque accumsan ipsum ac ipsum faucibus, id rutrum augue placerat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris elementum diam at massa ultricies, vel commodo felis dictum. Quisque dapibus auctor urna eu molestie. Duis lobortis fermentum fringilla. Proin sed est eu ante congue pretium. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam eget dapibus elit, quis rutrum ipsum. Aenean ut justo leo.
			Pellentesque ornare massa vitae dolor sagittis, eget tristique sapien pulvinar. Maecenas vitae pulvinar arcu, nec blandit mi. Quisque vel vestibulum nulla. Morbi porta, felis nec dignissim tincidunt, dolor nunc convallis lacus, nec blandit nisi ante ac ex. Nulla porta faucibus mi id condimentum. In sed placerat risus. Curabitur sed fringilla nisl, eu interdum nibh.
			Praesent justo massa, egestas vel ipsum nec, finibus porttitor ipsum. Quisque pulvinar lorem at egestas consequat. Vivamus sagittis tortor metus, eu consectetur tellus eleifend in. Quisque tempor lorem in neque interdum, eget commodo purus aliquet. Ut in lacinia sem, at finibus urna. In dapibus viverra dui, non luctus lacus scelerisque eu. In dui magna, tristique a faucibus feugiat, feugiat id lacus. Donec quis dapibus ex.
			Cras faucibus volutpat nisl id blandit. Mauris maximus mauris in mi aliquam, eget volutpat tortor tristique. Vestibulum felis lacus, pretium ac dolor non, dignissim euismod neque. Aenean ut lorem euismod, malesuada odio a, varius libero. Proin fringilla metus quam, ac cursus justo dapibus lobortis. Sed tempus finibus tortor eu rhoncus. Integer dapibus vehicula magna, ac cursus lacus porta sed. Pellentesque vel ligula id ante tempor volutpat. Proin ullamcorper vitae orci in vulputate. Aenean eget lectus at dolor porttitor consequat. Nam viverra neque in felis pellentesque ullamcorper.
			Nullam quis condimentum velit. Integer sodales quis eros ac lobortis. In id sapien tortor. Sed varius convallis dapibus. Aliquam vestibulum eget nisl eu mattis. Nulla interdum, ipsum quis feugiat lacinia, ante metus rutrum mauris, in convallis justo tortor in est. Duis ornare maximus libero, quis aliquet leo auctor ac. Aliquam vulputate lacus vel rutrum tincidunt.
			Sed tristique faucibus purus, a tempor diam vulputate ut. Nunc tincidunt orci ex, vitae aliquam lorem molestie non. Mauris ornare ex in magna tempor imperdiet. Nulla at molestie eros. Proin sodales consectetur nibh, at varius nibh. Nunc vitae ultrices enim. Sed tristique a ligula et rutrum. Proin non lectus vulputate, venenatis felis sed, luctus diam. Duis vitae nunc aliquet, semper arcu vitae, cursus odio. Sed non malesuada elit. Donec finibus, eros sit amet pulvinar hendrerit, urna risus cursus lectus, ullamcorper sollicitudin felis nibh vel arcu. Pellentesque sollicitudin, ligula ac imperdiet ultrices, arcu tortor viverra tortor, in euismod lorem tortor id nulla. Donec sed placerat lacus.
			Sed est orci, dapibus sed leo non, interdum vestibulum erat. Cras tempor nibh eros, eget feugiat mauris facilisis non. Nunc accumsan urna id enim faucibus, ac mattis elit mattis. Nulla consequat maximus ligula at aliquet. Aenean vitae pellentesque mi. Vivamus aliquam turpis at dignissim efficitur. Donec luctus enim eget justo egestas venenatis. Nullam scelerisque fermentum ligula. Integer pretium semper nisi malesuada varius. Sed ullamcorper quam augue, et pretium urna auctor id. In vitae urna nibh. Pellentesque suscipit tempus iaculis. Donec porttitor ante a eleifend luctus. Donec consequat purus at faucibus aliquet.
			Pellentesque nibh nunc, aliquet quis sem nec, rhoncus gravida ligula. Vestibulum vitae enim at nisl pellentesque iaculis. Ut iaculis nisl in sagittis dictum. Morbi vestibulum sit amet justo tristique scelerisque. Fusce facilisis vitae enim at vulputate. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi quis ligula ultrices, laoreet justo quis, aliquet tellus. Phasellus ultricies diam aliquet sollicitudin varius. Morbi porta, sem sit amet vulputate congue, eros urna pretium eros, non finibus risus lectus nec tortor. Fusce vel tincidunt nulla. Cras odio lectus, tincidunt ut efficitur eu, tristique id mi. Donec sodales magna erat, id dapibus nisl vulputate vitae. In sem purus, bibendum vitae feugiat et, commodo et nibh. Nam malesuada rutrum nunc et scelerisque. Vivamus placerat tristique ante, et consectetur odio imperdiet id. In pulvinar ac ante quis venenatis.
			Fusce ante magna, commodo sed justo sed, aliquam fringilla lorem. Proin feugiat velit eu nisi tincidunt hendrerit. Nullam odio justo, dapibus in felis sed, lobortis semper dolor. Integer nec semper dui, vitae fringilla libero. Sed sit amet feugiat nulla. Nunc quis hendrerit tortor, nec vehicula felis. Duis vel lacinia odio, nec iaculis lectus. Phasellus ac mollis metus, eget pellentesque metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque fringilla eu lorem porta hendrerit.
			Cras quam ante, posuere in laoreet ac, sollicitudin et lacus. Nullam ex metus, rutrum sed vestibulum eu, luctus nec urna. Fusce sed erat consequat, sagittis mauris ut, ornare erat. Vivamus laoreet gravida justo ac euismod. Ut vitae nisl quis dui mollis scelerisque. Quisque nec erat tortor. Proin ac rhoncus nisl, ut pulvinar lorem. Donec tristique ligula vitae felis ornare, non volutpat metus bibendum. Ut at libero nulla. Vestibulum erat elit, molestie et magna a, vestibulum suscipit ipsum. Praesent molestie volutpat mauris, eu consequat magna consequat nec.
			Nunc vitae purus sodales, ullamcorper nibh vel, fermentum tellus. Nunc nunc magna, rhoncus sed consequat eu, accumsan sed purus. In sit amet ante tristique, tincidunt ipsum et, convallis metus. Curabitur ex metus, commodo id quam pharetra, congue sagittis orci. Proin nec ultrices augue, at laoreet velit. Mauris vulputate nulla id enim pellentesque, sed tempor est ultricies. Maecenas sed venenatis quam, nec dapibus massa. Vivamus a urna in felis tincidunt maximus. Morbi posuere ut libero at luctus.
			Maecenas porttitor orci ut arcu fringilla, eget venenatis lacus porttitor. Sed semper elit eget viverra sollicitudin. In finibus magna eu tortor tincidunt, vitae aliquam sapien egestas. Integer enim felis, ultricies nec dapibus eu, bibendum et augue. Aliquam lacinia nunc sollicitudin eros vehicula placerat. Cras nisl erat, semper sit amet feugiat vitae, iaculis nec tellus. Proin quis leo luctus, consequat nisi placerat, volutpat ex. In tortor mauris, convallis a risus id, tincidunt luctus ante. In facilisis rhoncus gravida. Donec rutrum ac lacus sed porttitor. Sed tortor ante, vulputate sed eleifend in, dapibus non massa. Pellentesque ut ante urna. Sed diam nisl, commodo nec neque accumsan, tincidunt sagittis arcu. Nulla egestas quis quam in ultrices. Praesent efficitur tincidunt orci id ultricies.
			Sed felis orci, interdum in augue id, dictum sodales velit. Nullam enim ipsum, volutpat at accumsan mollis, imperdiet vel dui. Quisque porttitor mauris vitae risus tempus, at pharetra nisi tempus. Donec rhoncus semper metus, sit amet malesuada ipsum iaculis gravida. Etiam maximus ante sit amet commodo eleifend. Suspendisse consequat, orci ut placerat varius, nulla massa auctor sem, et aliquet lectus lectus sit amet nulla. In vestibulum vulputate lorem, vitae suscipit massa tincidunt quis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer ac commodo elit, ut feugiat dui. Sed lacus dui, pulvinar in porttitor id, vulputate ac turpis. In at bibendum enim. Phasellus gravida erat diam, vitae sodales mi dapibus vitae. Nam non lobortis nisi, sit amet faucibus ex. Cras pharetra dui magna, vitae cursus leo tempor porttitor.
			Quisque ac lorem vulputate, malesuada ante ac, porttitor quam. Fusce vitae aliquet ipsum. Suspendisse potenti. Morbi in magna pretium felis elementum aliquet. Integer vitae tincidunt ipsum, sit amet auctor urna. Morbi et aliquam diam. Sed at sodales odio. Aenean condimentum lorem orci, sit amet placerat risus aliquam vel. Proin vitae justo sit amet quam consequat dapibus et quis elit. Curabitur quis nisi dolor. Aliquam quis eleifend justo, at consectetur massa.
			Fusce ut vulputate odio. Maecenas volutpat et neque euismod tempus. Phasellus sed ligula mauris. Aenean facilisis tortor sit amet consectetur tristique. Etiam pulvinar elit massa, et dictum justo elementum eget. Nunc vulputate placerat pulvinar. Sed nibh tellus, volutpat at viverra id, scelerisque ac purus. Ut luctus venenatis ex. Vivamus ante sapien, ultrices ac nisl eget, vestibulum consectetur ante. Fusce et mauris varius ipsum ornare facilisis at nec ligula. Praesent et dignissim orci. Nam id felis nulla. Etiam commodo nulla nec sodales gravida.
			Nam dignissim convallis tellus, eget tincidunt risus ornare sit amet. Etiam id quam cursus nibh placerat ultrices. Nunc vitae facilisis eros. Aliquam lacinia, ipsum quis vulputate lacinia, magna ante luctus orci, in scelerisque est nibh a ipsum. Vestibulum sodales purus vel nisi viverra, quis varius arcu consectetur. Quisque condimentum congue sodales. Aenean pharetra placerat eleifend. Praesent feugiat odio elit, at euismod nunc varius a. Pellentesque fermentum ante felis, vel interdum arcu interdum ac. Quisque iaculis elementum dui et luctus.
			Nam cursus commodo lacus ut consequat. Etiam sapien urna, pulvinar id nibh at, vestibulum consectetur ante. Sed dignissim et velit vel volutpat. Vestibulum ut orci hendrerit, aliquet nisi sit amet, sodales mauris. Nulla facilisi. Suspendisse non vestibulum mauris, ut ornare odio. Duis elementum fermentum nunc, a vestibulum justo. Nulla imperdiet pharetra tempus. Quisque leo nibh, malesuada eget erat quis, laoreet malesuada nulla. Ut congue diam diam. Aliquam sodales, arcu a facilisis volutpat, elit ligula porttitor orci, non dapibus mi velit sit amet nisi. Curabitur suscipit, risus sit amet condimentum pretium, lectus metus commodo orci, a imperdiet odio tortor non leo. Suspendisse suscipit sollicitudin gravida. Nullam ultricies risus ut purus auctor aliquet. Phasellus efficitur laoreet nibh semper facilisis.
			Duis et lectus turpis. Sed dapibus vitae quam quis porttitor. Nullam bibendum nisl nec elit venenatis cursus id id augue. Duis at dui ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin ut urna vel elit consectetur venenatis. Praesent ullamcorper egestas orci, eleifend euismod leo gravida nec. Nulla nec molestie felis, quis eleifend sapien. Sed faucibus quam orci, at consequat sem fermentum sed.
			Proin lacinia massa leo, sed tincidunt urna ultrices vel. Mauris in elit quis diam dapibus viverra eu at purus. Vestibulum consequat placerat porta. Donec id bibendum nibh, eu vehicula velit. Proin bibendum enim nulla, non elementum lectus ultrices et. Aliquam in ultricies nibh, vitae efficitur leo. In eleifend elit sit amet nibh faucibus, ut dictum lacus placerat. Quisque sed nibh diam. Nullam egestas ante ac augue tristique, vel blandit dolor ultrices. Aliquam finibus finibus quam ac malesuada. Fusce sit amet magna leo.
			Nulla eu lacus purus. Integer sit amet nunc quis lacus finibus porttitor. Vivamus elit metus, sodales sit amet velit eu, egestas ullamcorper turpis. Mauris convallis lacinia quam, a rutrum urna dictum et. Donec quam tellus, venenatis non diam suscipit, suscipit facilisis quam. Vestibulum imperdiet turpis volutpat enim dictum vestibulum. Ut auctor, purus ac iaculis venenatis, sem sapien congue turpis, eget viverra urna sem vitae lorem. Nam ornare lacinia lorem nec ultrices. Quisque at elit faucibus, semper nunc nec, pellentesque augue. Integer vitae odio erat. Ut sit amet efficitur risus.
			Duis viverra, orci aliquam euismod dignissim, ante orci efficitur nunc, id placerat ex nisi sit amet purus. Aenean sit amet feugiat leo. Curabitur vestibulum velit eget dolor semper mollis. Vestibulum ut dictum dui, ut ultrices risus. Cras in nunc dignissim, feugiat ligula consequat, faucibus dui. Suspendisse dignissim in urna eget facilisis. Quisque eu tincidunt est. Ut eget lacus ultricies, ornare turpis at, molestie purus. Sed neque est, egestas eget hendrerit sit amet, convallis eu urna.
			Mauris scelerisque non tortor at mattis. Nulla vestibulum erat a risus finibus maximus. Phasellus sit amet urna orci. Pellentesque sed posuere purus, tempus elementum neque. Mauris dictum, nisl id pulvinar sagittis, ante sem fringilla magna, sit amet ullamcorper diam ex quis nisl. Integer tincidunt sodales tortor vel tempor. Ut ut lectus quis tellus suscipit finibus non ornare felis. Mauris sed lorem viverra, eleifend dui sit amet, vestibulum metus. Suspendisse potenti. Maecenas id nunc quis sem dictum rutrum. In gravida sit amet arcu sit amet gravida. Donec egestas metus sed suscipit scelerisque.
			Mauris eget interdum elit, ac varius arcu. Suspendisse potenti. Nulla maximus nulla ac urna blandit dictum. Cras faucibus ipsum erat, non pellentesque velit sollicitudin ut. Duis lacus urna, cursus sit amet mollis quis, volutpat non ante. Praesent massa ligula, mattis lobortis fermentum consectetur, fringilla vel nunc. Mauris finibus fermentum molestie. Cras porta tincidunt metus vitae varius.
			Morbi euismod odio quis libero semper tincidunt. Donec ultricies molestie est, id porttitor ligula dapibus vitae. Proin dui nulla, semper a tellus eget, facilisis hendrerit libero. Mauris lacinia fermentum elit sit amet facilisis. Nunc tristique vulputate ex, nec convallis neque faucibus vitae. Duis at mi rutrum mauris aliquam lacinia. Proin egestas nec augue eu dictum. Aenean id tempus mi. Praesent vestibulum nisi in mollis interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse eros mauris, aliquam sit amet suscipit at, viverra ut quam. Morbi ullamcorper eget libero nec rutrum. Nam suscipit, libero at cursus tincidunt, massa risus cursus sem, eget sagittis eros nulla vitae felis. Praesent feugiat laoreet justo, aliquam varius neque dignissim et.
			Integer bibendum felis arcu, vel placerat est interdum ut. Quisque eget congue felis, sed dictum nulla. Sed vitae eros maximus, iaculis odio sollicitudin, consectetur justo. Curabitur dolor leo, dapibus cursus accumsan quis, vestibulum eget elit. Maecenas eget elit sit amet magna hendrerit aliquet. Integer libero justo, maximus et quam in, pharetra pharetra nibh. Nunc dolor nibh, condimentum non malesuada non, vehicula id justo. Suspendisse non molestie neque. Vestibulum ut porttitor elit. Pellentesque vehicula accumsan leo, vel lacinia orci scelerisque quis. Sed sapien arcu, lobortis dignissim dui at, varius mollis leo. Suspendisse pretium urna nec metus tincidunt, consequat blandit odio consectetur. Nulla blandit dolor interdum est porta congue. Proin non blandit erat.
			Donec a dui orci. Cras lobortis lacus vitae enim scelerisque, eu pharetra erat pretium. Fusce in porttitor purus. Duis consequat nisi sit amet ultrices volutpat. Ut pharetra bibendum enim et molestie. Aliquam eget velit id neque pretium convallis. Pellentesque quis ante eu orci feugiat fringilla non ut metus. Etiam augue libero, gravida aliquet volutpat at, efficitur non dui. Praesent molestie eros quis arcu egestas, consectetur faucibus eros cursus. Etiam ipsum nibh, eleifend ac lacus eu, mollis iaculis ligula. Nam elementum, lacus nec semper sagittis, diam ex maximus justo, quis viverra sem tortor eget ante.
			Nam tincidunt, felis in aliquet pharetra, justo tellus pellentesque quam, eu ullamcorper enim ex ut erat. Integer lectus turpis, fermentum ac molestie nec, accumsan a lectus. Ut faucibus mi vel accumsan faucibus. Donec nec dui et augue tempus placerat. Donec augue libero, posuere a odio non, aliquam ullamcorper dui. Proin condimentum mauris ac odio faucibus eleifend. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sed dolor eu urna molestie auctor. Phasellus a metus neque. Aliquam erat volutpat. Nullam urna urna, dapibus vitae pulvinar gravida, eleifend accumsan ex. Etiam ligula lorem, ultrices sit amet nibh eget, porttitor pretium ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
			Sed lacinia in augue ut accumsan. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut in urna mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam ex lorem, ultrices ut egestas eu, dignissim ut neque. Etiam risus ligula, fringilla quis ante eu, pharetra porta tellus. Ut scelerisque, lorem non malesuada placerat, urna ligula facilisis purus, sit amet rhoncus velit elit euismod sem. Aenean sed finibus lorem.
			Integer fermentum tellus tortor, at placerat diam varius in. Nam auctor feugiat accumsan. Duis nec ante vitae ex elementum lobortis. Integer sit amet quam dictum, vulputate est in, vulputate quam. Suspendisse volutpat tempor urna ut auctor. Donec eleifend erat magna. In hac habitasse platea dictumst. Mauris tempor, massa vitae laoreet viverra, nulla nisi bibendum ligula, a mollis purus nulla sit amet lacus. Donec non eros nec nibh dapibus feugiat. Curabitur tincidunt ac lacus sit amet pretium. Nam erat diam, aliquet bibendum erat sed, imperdiet molestie tortor. Donec quis urna ac sem pulvinar pellentesque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris eu euismod nisl. Nulla a ultrices tellus.
			Vivamus quis volutpat risus. Suspendisse lobortis tortor ac dolor hendrerit rhoncus. Aenean risus dui, suscipit eu tortor quis, tempus eleifend nibh. Ut eu tincidunt sapien, at laoreet nisi. Sed orci purus, sollicitudin sed dignissim at, ultrices eu turpis. Fusce orci sem, hendrerit malesuada ligula at, porttitor lobortis urna. Nunc dui ipsum, tincidunt id ligula in, sollicitudin vulputate tellus. Sed auctor ex sed facilisis congue. Nam nibh mi, sodales ac venenatis non, consectetur id est. Proin gravida maximus ligula quis egestas.
			Curabitur ornare velit eu ipsum iaculis elementum. Cras ac quam vel neque gravida pulvinar vitae at ante. Vivamus ultrices vel velit eu ornare. Nullam placerat dolor dolor, ut elementum sem lobortis vehicula. Nunc quis gravida lorem, et rutrum eros. Cras mattis, sapien eu semper rhoncus, massa orci faucibus enim, ut feugiat elit mauris sit amet risus. Morbi egestas ante et felis imperdiet feugiat nec nec leo. Praesent fringilla vitae nulla eget bibendum. Sed id ullamcorper dui. In blandit neque lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Duis pellentesque ut leo vel congue. Etiam turpis tortor, pulvinar nec lorem eu, vulputate egestas justo. Vestibulum ultrices purus tortor, in aliquam lectus aliquet sit amet.
			Praesent faucibus, erat nec pharetra vulputate, leo neque rutrum justo, eu sagittis ligula risus in dui. Phasellus non varius ipsum. Maecenas vehicula nisl vel nunc ornare rhoncus. Fusce bibendum imperdiet lacus, non tristique lectus maximus nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec arcu sit amet est condimentum maximus. Morbi at libero orci. Phasellus pulvinar eros magna, at elementum massa condimentum nec. Nunc finibus sollicitudin orci, a consequat velit.
			Maecenas euismod massa ut dui aliquam, id facilisis augue consectetur. Aenean nibh lorem, euismod non velit nec, volutpat laoreet metus. Aenean lorem sem, suscipit eget erat id, ornare tempus ex. Pellentesque vestibulum augue urna, eget hendrerit magna consequat sed. Sed lacinia hendrerit arcu, volutpat dignissim massa iaculis in. Duis mollis mi vel luctus iaculis. Cras mauris nunc, imperdiet sed nulla vel, convallis rhoncus felis. Donec eget felis mollis, euismod orci non, laoreet leo.
			 """;
	
}
